% \VignetteIndexEntry{ichorCNA}
% \VignetteDepends{ichorCNA, HMMcopy}

\title{ichorCNA: Estimation of tumor fraction in cell-free DNA from ultra-low-pass whole genome sequencing.}
\author{Gavin Ha, Justin Rhoades, Samuel Freeman}
\date{\today}

\begin{document}

\maketitle
\tableofcontents

\section{Introduction}

ichorCNA is a tool for estimating the fraction of tumor in ultra-low-pass whole genome sequencing (ULP-WGS) of cell-free DNA.

\section{Analysis}

<<>>=
library(HMMcopy)
tumor_file <- system.file("extdata", "MBC_315.ctDNA.reads.wig",
                      package = "ichorCNA")

tumor_reads <- wigToRangedData(tumor_file)
@

\end{document}